name: Build JOSS paper draft

on:
  push:
    paths:
      - paper.md
      - paper.bib
      - .github/workflows/paper-draft.yml
  pull_request:
    paths:
      - paper.md
      - paper.bib
      - .github/workflows/paper-draft.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build PDF draft
        uses: openjournals/openjournals-draft-action@v1
        with:
          journal: joss
          paper-path: paper.md
